### ISSUE TITLE
MIW Service fails to start in the cluster

### ISSUE THREAD

**Issue by hemantxpatel** [eclipse-tractusx/tutorial-resources#104]
## Description
MIW is failing to start while running mxd.

## How to reproduce
* Follow steps mentioned in readme upto `terraform apply`
* Check console output for failure.

## Additional Info
MIW Pod Startup Logs
```
Caused by: java.lang.RuntimeException: JsonLdError[code=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED]., message=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].]
	at org.eclipse.tractusx.ssi.lib.proof.transform.LinkedDataTransformer.toDataset(LinkedDataTransformer.java:82) ~[cx-ssi-lib-0.0.16.jar!/:na]
	at org.eclipse.tractusx.ssi.lib.proof.transform.LinkedDataTransformer.transform(LinkedDataTransformer.java:50) ~[cx-ssi-lib-0.0.16.jar!/:na


Caused by: com.apicatalog.jsonld.JsonLdError: Unexpected response code [524]
	at com.apicatalog.jsonld.loader.DefaultHttpLoader.loadDocument(DefaultHttpLoader.java:95) ~[titanium-json-ld-1.3.2.jar!/:na]
	at com.apicatalog.jsonld.loader.HttpLoader.loadDocument(HttpLoader.java:6) ~[titanium-json-ld-1.3.2.jar!/:na]
	at org.eclipse.tractusx.ssi.lib.model.RemoteDocumentLoader.loadDocument(RemoteDocumentLoader.java:95) ~[cx-ssi-lib-0.0.16.jar!/:na]
	at com.apicatalog.jsonld.context.ActiveContextBuilder.fetch(ActiveContextBuilder.java:535) ~[titanium-json-ld-1.3.2.jar!/:na]
	... 81 common frames omitted
```

**Comment by wolf4ood** [comment]
Hi @hemantxpatel 

it's related to this MIW issue https://github.com/eclipse-tractusx/managed-identity-wallet/issues/103.

This will be resolved once the fix it's merged and the docker image it's release

**Comment by hemantxpatel** [comment]
Thanks @wolf4ood

**Comment by SantoshDeepak1** [comment]
While creating wallet in MIW the issue is still there. 

```
Caused by: com.apicatalog.jsonld.JsonLdError: There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].
	at com.apicatalog.jsonld.context.ActiveContextBuilder.fetch(ActiveContextBuilder.java:539) ~[titanium-json-ld-1.3.2.jar!/:na]
	at com.apicatalog.jsonld.context.ActiveContextBuilder.create(ActiveContextBuilder.java:174) ~[titanium-json-ld-1.3.2.jar!/:na]
	at com.apicatalog.jsonld.expansion.ObjectExpansion.initLocalContext(ObjectExpansion.java:200) ~[titanium-json-ld-1.3.2.jar!/:na]
	at com.apicatalog.jsonld.expansion.ObjectExpansion.expand(ObjectExpansion.java:102) ~[titanium-json-ld-1.3.2.jar!/:na]
	at com.apicatalog.jsonld.expansion.Expansion.compute(Expansion.java:119) ~[titanium-json-ld-1.3.2.jar!/:na]
	at com.apicatalog.jsonld.processor.ExpansionProcessor.expand(ExpansionProcessor.java:124) ~[titanium-json-ld-1.3.2.jar!/:na]
	at com.apicatalog.jsonld.processor.ToRdfProcessor.toRdf(ToRdfProcessor.java:69) ~[titanium-json-ld-1.3.2.jar!/:na]
	at com.apicatalog.jsonld.api.ToRdfApi.get(ToRdfApi.java:166) ~[titanium-json-ld-1.3.2.jar!/:na]
	at org.eclipse.tractusx.ssi.lib.proof.transform.LinkedDataTransformer.toDataset(LinkedDataTransformer.java:80) ~[cx-ssi-lib-0.0.16.jar!/:na]
	... 168 common frames omitted
Caused by: com.apicatalog.jsonld.JsonLdError: Unexpected response code [524]
	at com.apicatalog.jsonld.loader.DefaultHttpLoader.loadDocument(DefaultHttpLoader.java:95) ~[titanium-json-ld-1.3.2.jar!/:na]
	at com.apicatalog.jsonld.loader.HttpLoader.loadDocument(HttpLoader.java:6) ~[titanium-json-ld-1.3.2.jar!/:na]
	at org.eclipse.tractusx.ssi.lib.model.RemoteDocumentLoader.loadDocument(RemoteDocumentLoader.java:95) ~[cx-ssi-lib-0.0.16.jar!/:na]
	at com.apicatalog.jsonld.context.ActiveContextBuilder.fetch(ActiveContextBuilder.java:535) ~[titanium-json-ld-1.3.2.jar!/:na]
	... 176 common frames omitted

```

**Comment by hemantxpatel** [comment]
It has been resolved via above linked PR.
