### ISSUE TITLE
STS Runtime not getting started

### ISSUE THREAD

**Issue by hemantxpatel** [eclipse-tractusx/tutorial-resources#494]
### Current Behavior

After building `mxd-runtimes` and then deploying pods after running `terraform apply`, `sts` pod is not coming up.

### Expected Behavior

It should be getting started.

### Steps To Reproduce

Follow readme instructions to deploy application.

### Stack Trace
```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2024-12-05 06:42:14:787 +0000] [main] ERROR io.opentelemetry.javaagent.tooling.config.ConfigurationPropertiesSupplier - Configuration file "/app/opentelemetry.properties" not found.
[otel.javaagent 2024-12-05 06:42:14:804 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.32.0
OpenTelemetry Javaagent failed to start
java.lang.ExceptionInInitializerError
	at io.opentelemetry.javaagent.tooling.muzzle.AgentTooling.<clinit>(AgentTooling.java:23)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:151)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:103)
	at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:98)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer$1.run(AgentInitializer.java:53)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer$1.run(AgentInitializer.java:47)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.execute(AgentInitializer.java:64)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:46)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:57)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:45)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @2ff4f00f
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
```

**Comment by paullatzelsperger** [comment]
you can ignore that. this is coming from OpenTelemetry, and nothing we can control.

**Comment by hemantxpatel** [comment]
sts pod was somehow got stuck everytime when I tried earlier, and I thought the above error might be the cause. But I am able to run it now. Thanks.
